const { generateStructuredPlan, generateConversational } = require('./gemini.service');
const { generateConversationalResponse, generateStructuredFallback } = require('./groq.service');

// Wrapper to handle Gemini -> Groq fallback and validation
const generateWithFallback = async (systemInstruction, prompt, type) => {
  const validator = (data) => {
    if (!data) return false;
    if (type === 'workout') return Array.isArray(data.weeklyPlan);
    if (type === 'nutrition') return !!data.dailyTarget && Array.isArray(data.meals);
    if (type === 'meal') return Array.isArray(data.days);
    return true;
  };

  try {
    console.log(`[AI] ${type} generation started`);
    
    if (type === 'nutrition' || type === 'meal') {
      console.log(`[AI] Bypassing Gemini for ${type}, forcing Groq`);
      throw new Error("Forcing Groq for this type");
    }
    
    console.log("[AI] Trying Gemini");
    const result = await generateStructuredPlan(systemInstruction, prompt);
    if (!validator(result)) throw new Error("Invalid schema generated");
    console.log("[AI] Gemini generation successful");
    return result;
  } catch (error) {
    console.log(`[AI] Gemini failed: ${error.message}`);
    console.log("[AI] Falling back to Groq");
    
    try {
      const fallbackResult = await generateStructuredFallback(systemInstruction, prompt);
      if (!validator(fallbackResult)) throw new Error("Invalid schema generated by fallback");
      console.log("[AI] Groq generation successful");
      return fallbackResult;
    } catch (fallbackError) {
      console.log("[AI] Groq fallback failed");
      if (fallbackError.status) {
        throw fallbackError;
      }
      const err = new Error("AI service is temporarily unavailable. Please try again shortly.");
      err.code = "AI_SERVICE_UNAVAILABLE";
      err.status = 503;
      throw err;
    }
  }
};

const generateChatbotFallback = async (systemInstruction, messages) => {
  try {
    const groqMessages = [
      { role: "system", content: systemInstruction },
      ...messages
    ];
    return await generateConversationalResponse(groqMessages);
  } catch (err) {
    if (err.status) throw err;
    const e = new Error("AI service is temporarily unavailable.");
    e.status = 503;
    throw e;
  }
};

const generateChatbotResponse = async (message, history, aiContext) => {
  const systemInstruction = `You are "FitZone AI", a helpful, personal fitness and nutrition assistant built natively into the FitZone platform.
Your job is to provide practical, concise fitness and nutrition advice, formatted beautifully in Markdown.

CORE RULES:
1. Give practical and concise answers. Do not write essays. Use bullet points or short paragraphs.
2. If the user asks about their own plans, use the attached User Context below. 
3. If they ask about today's workout, refer to 'Active Workout'.
4. If they ask about calories/macros, refer to 'Active Nutrition'.
5. Do NOT invent user data. If personalized data is unavailable in the context, politely ask them to create a plan in the FitZone dashboard.
6. Do NOT generate raw JSON. You must output human-readable conversational text.
7. For deep/premium coaching requests, recommend they use "FitZone AI Coach".
8. Do NOT claim you can automatically log/mark workouts as completed.
9. For health/safety conditions or injuries, always advise seeking professional medical help.

USER CONTEXT:
${aiContext ? JSON.stringify(aiContext, null, 2) : "User is unauthenticated. Give general advice only."}`;

  const messages = [...history, { role: "user", content: message }];

  try {
    return await generateConversational(systemInstruction, messages);
  } catch (error) {
    console.log("[AI] Chatbot Gemini failed, falling back to Groq");
    return await generateChatbotFallback(systemInstruction, messages);
  }
};

const generateWorkoutPlan = async (userProfile, requirements) => {
  const systemInstruction = `You are a professional FitZone AI Fitness Coach. 
Generate a personalized weekly workout plan based on the user's profile and requirements.
Return the result STRICTLY as a JSON object with this exact structure:
{
  "goal": "Weight Loss",
  "weeklyPlan": [
    {
      "day": "Monday",
      "workoutName": "Upper Body Strength",
      "duration": "45 min",
      "difficulty": "Intermediate",
      "targetMuscle": "Chest, Back, Arms",
      "exercises": [
        {
          "name": "Bench Press",
          "sets": 3,
          "reps": "10-12",
          "restTime": "60s",
          "instructions": "Keep back flat on bench"
        }
      ]
    }
  ]
}
Do NOT include any markdown formatting, only pure JSON.`;

  const prompt = `User Profile:
${JSON.stringify(userProfile, null, 2)}

Requirements:
${JSON.stringify(requirements, null, 2)}

Please generate the weekly workout plan.`;

  return generateWithFallback(systemInstruction, prompt, 'workout');
};

const generateNutritionPlan = async (userProfile, requirements) => {
  const systemInstruction = `You are a professional FitZone AI Nutritionist.
Generate a personalized daily nutrition and meal plan based on the user's profile and requirements.
Return the result STRICTLY as a JSON object with this exact structure:
{
  "dailyTarget": {
    "calories": 2400,
    "protein": "150g",
    "carbs": "280g",
    "fat": "70g"
  },
  "meals": [
    {
      "mealName": "Breakfast",
      "ingredients": "Oatmeal, Eggs",
      "calories": 520,
      "protein": "32g",
      "carbs": "50g",
      "fat": "15g",
      "prepTime": "10 min",
      "instructions": "Boil oats, scramble eggs."
    }
  ]
}
Do NOT include any markdown formatting, only pure JSON.`;

  const prompt = `User Profile:
${JSON.stringify(userProfile, null, 2)}

Requirements:
${JSON.stringify(requirements, null, 2)}

Please generate the daily nutrition plan.`;

  return generateWithFallback(systemInstruction, prompt, 'nutrition');
};

const generateMealPlan = async (userProfile, requirements) => {
  const { country, duration, calories, dietary, budget } = requirements;
  
  const systemInstruction = `You are a FitZone AI Meal Planner specializing in hyper-local, country-aware diets.
The user is from ${country}. Generate a practical ${duration}-day meal plan based PRIMARILY on commonly consumed local foods and eating patterns in ${country}.
Do NOT simply translate Western meals unless they are culturally appropriate and accessible.
Budget preference: ${budget}. Estimate costs in the local currency.

Return the result STRICTLY as a JSON object with this EXACT structure:
{
  "currencyCode": "Local Currency Code (e.g. BDT, INR, USD)",
  "currencySymbol": "Symbol (e.g. ৳, ₹, $)",
  "estimatedCost": "Numeric string (e.g. 2500)",
  "days": [
    {
      "dayNumber": 1,
      "meals": [
        {
          "mealCategory": "Breakfast",
          "mealName": "Local breakfast item",
          "calories": 400,
          "protein": "15g",
          "carbs": "50g",
          "fat": "10g",
          "prepTime": "15 min",
          "ingredients": "Local ingredients",
          "instructions": "Brief prep steps"
        }
      ]
    }
  ]
}
Generate exactly ${duration} days. Do NOT include any markdown formatting, only pure JSON.`;

  const prompt = `User Profile:
${JSON.stringify(userProfile, null, 2)}

Requirements:
Target Calories: ${calories}
Dietary Restrictions: ${dietary}
Budget: ${budget}
Duration: ${duration} days
Country/Cuisine Focus: ${country}

Please generate the local meal plan now.`;

  return generateWithFallback(systemInstruction, prompt, 'meal');
};

const generateCoachResponse = async (conversationHistory, userProfile) => {
  const systemInstruction = `You are the FitZone AI Coach, a highly knowledgeable and encouraging fitness assistant.
You provide personalized fitness, workout, and nutrition advice.
Keep your answers concise, practical, and formatted beautifully using markdown.
Do NOT provide guaranteed medical diagnoses.
Disclaimer: Remind the user if necessary that AI-generated suggestions are for general informational purposes.
User Profile context: ${JSON.stringify(userProfile)}`;

  try {
    return await generateConversational(systemInstruction, conversationHistory);
  } catch (error) {
    console.log("[AI] Coach Gemini failed, falling back to Groq");
    try {
      const groqMessages = [
        { role: "system", content: systemInstruction },
        ...conversationHistory
      ];
      return await generateConversationalResponse(groqMessages);
    } catch (fallbackError) {
      if (fallbackError.status) throw fallbackError;
      const e = new Error("AI Coach service is temporarily unavailable.");
      e.status = 503;
      throw e;
    }
  }
};

module.exports = {
  generateWorkoutPlan,
  generateNutritionPlan,
  generateMealPlan,
  generateCoachResponse,
  generateChatbotResponse
};
